from ALL_LOCUS_DATA import *

# 1, 5, 6
TORSO_OPTIMAL_GENE_COMBO = [LOCI_1[2], LOCI_5[1], LOCI_6[2]]
TORSO_GOOD_GENE_COMBO = [LOCI_1[3], LOCI_5[2], LOCI_6[3]]
TORSO_BAD_GENE_COMBO = [LOCI_1[4], LOCI_5[3], LOCI_6[4]]
TORSO_WORST_GENE_COMBO = [LOCI_1[2], LOCI_5[1], LOCI_6[5]]

# 1, 6, 7
ARM_LENGTH_OPTIMAL_GENE_COMBO = [LOCI_1[2], LOCI_6[1], LOCI_7[0]]
ARM_LENGTH_GOOD_GENE_COMBO = [LOCI_1[3], LOCI_6[2], LOCI_7[5]]
ARM_LENGTH_BAD_GENE_COMBO = [LOCI_1[4], LOCI_6[3], LOCI_7[1]]
ARM_LENGTH_WORST_GENE_COMBO = [LOCI_1[2], LOCI_6[1], LOCI_7[1]]

# 4, 9
LEG_LENGTH_OPTIMAL_GENE_COMBO = [LOCI_4[3], LOCI_9[5]]
LEG_LENGTH_GOOD_GENE_COMBO = [LOCI_4[4], LOCI_9[4]]
LEG_LENGTH_BAD_GENE_COMBO = [LOCI_4[5], LOCI_9[3]]
LEG_LENGTH_WORST_GENE_COMBO = [LOCI_4[2], LOCI_9[3]]

# 6, 18
MUSCLULATURE_OPTIMAL_GENE_COMBO = [LOCI_6[11], LOCI_18[1]]
MUSCLULATURE_GOOD_GENE_COMBO = [LOCI_6[2], LOCI_18[4]]
MUSCLULATURE_BAD_GENE_COMBO = [LOCI_6[3], LOCI_18[2]]
MUSCLULATURE_WORST_GENE_COMBO = [LOCI_6[4], LOCI_18[2]]

# 10, 20
METABOLISM_OPTIMAL_GENE_COMBO = [LOCI_10[2], LOCI_20[5]]
METABOLISM_GOOD_GENE_COMBO = [LOCI_10[3], LOCI_20[4]]
METABOLISM_BAD_GENE_COMBO = [LOCI_10[5], LOCI_20[3]]
METABOLISM_WORST_GENE_COMBO = [LOCI_10[1], LOCI_20[5]]

# 13, 18
FLEXIBILITY_OPTIMAL_GENE_COMBO = [LOCI_13[2], LOCI_18[5]]
FLEXIBILITY_GOOD_GENE_COMBO = [LOCI_13[3], LOCI_18[1]]
FLEXIBILITY_BAD_GENE_COMBO = [LOCI_13[1], LOCI_18[0]]
FLEXIBILITY_WORST_GENE_COMBO = [LOCI_13[3], LOCI_18[2]]

# 23, 24
PAIN_TOLERANCE_OPTIMAL_GENE_COMBO = [LOCI_23[2], LOCI_24[0]]
PAIN_TOLERANCE_GOOD_GENE_COMBO = [LOCI_23[3], LOCI_24[4]]
PAIN_TOLERANCE_BAD_GENE_COMBO = [LOCI_23[4], LOCI_24[2]]
PAIN_TOLERANCE_WORST_GENE_COMBO = [LOCI_23[1], LOCI_24[2]]

#1, 2, 3
EYE_COLOR_OPTIMAL_GENE_COMBO = [LOCI_1[1], LOCI_2[11], LOCI_3[0]]
EYE_COLOR_GOOD_GENE_COMBO = [LOCI_1[0], LOCI_2[7], LOCI_3[1]]
EYE_COLOR_BAD_GENE_COMBO = [LOCI_1[4], LOCI_2[2], LOCI_3[2]]
EYE_COLOR_WORST_GENE_COMBO = [LOCI_1[1], LOCI_2[1], LOCI_3[3]]

# 6, 11
VISION_OPTIMAL_GENE_COMBO = [LOCI_6[2], LOCI_11[0]]
VISION_GOOD_GENE_COMBO = [LOCI_6[1], LOCI_11[0]]
VISION_BAD_GENE_COMBO = [LOCI_6[4], LOCI_11[3]]
VISION_WORST_GENE_COMBO = [LOCI_6[2], LOCI_11[0]]

# 10, 22
HEARING_OPTIMAL_GENE_COMBO = [LOCI_10[2], LOCI_22[3]]
HEARING_GOOD_GENE_COMBO = [LOCI_10[1], LOCI_22[0]]
HEARING_BAD_GENE_COMBO = [LOCI_10[4], LOCI_22[3]]
HEARING_WORST_GENE_COMBO = [LOCI_10[2], LOCI_22[0]]

# 7, 9
BLOOD_TYPE_OPTIMAL_GENE_COMBO = [LOCI_7[2], LOCI_9[1]]
BLOOD_TYPE_GOOD_GENE_COMBO = [LOCI_7[3], LOCI_9[2]]
BLOOD_TYPE_BAD_GENE_COMBO = [LOCI_7[1], LOCI_9[3]]
BLOOD_TYPE_WORST_GENE_COMBO = [LOCI_7[2], LOCI_9[1]]

# 11, 18
LUNG_CAPACITY_OPTIMAL_GENE_COMBO = [LOCI_11[2], LOCI_18[5]]
LUNG_CAPACITY_GOOD_GENE_COMBO = [LOCI_11[3], LOCI_18[4]]
LUNG_CAPACITY_BAD_GENE_COMBO = [LOCI_11[4], LOCI_18[3]]
LUNG_CAPACITY_WORST_GENE_COMBO = [LOCI_11[2], LOCI_18[1]]

# 20, 21
REGENERATION_OPTIMAL_GENE_COMBO = [LOCI_20[2], LOCI_21[5]]
REGENERATION_GOOD_GENE_COMBO = [LOCI_20[3], LOCI_21[4]]
REGENERATION_BAD_GENE_COMBO = [LOCI_20[4], LOCI_21[3]]
REGENERATION_WORST_GENE_COMBO = [LOCI_20[2], LOCI_21[1]]

# 2, 8
HAIR_COLOR_OPTIMAL_GENE_COMBO = [LOCI_2[11], LOCI_8[2]]
HAIR_COLOR_GOOD_GENE_COMBO = [LOCI_2[2], LOCI_8[5]]
HAIR_COLOR_BAD_GENE_COMBO = [LOCI_2[3], LOCI_8[2]]
HAIR_COLOR_WORST_GENE_COMBO = [LOCI_2[1], LOCI_8[1]]

# 2, 8, 19
HAIR_TYPE_OPTIMAL_GENE_COMBO = [LOCI_2[11], LOCI_8[2], LOCI_19[11]]
HAIR_TYPE_GOOD_GENE_COMBO = [LOCI_2[0], LOCI_8[5], LOCI_19[1]]
HAIR_TYPE_BAD_GENE_COMBO = [LOCI_2[5], LOCI_8[4], LOCI_19[8]]
HAIR_TYPE_WORST_GENE_COMBO = [LOCI_2[1], LOCI_8[2], LOCI_19[3]]

# 19, 25, 28, 29
BRAIN_TYPE_OPTIMAL_GENE_COMBO = [LOCI_19[11], LOCI_25[0], LOCI_28[0], LOCI_29[0]]
BRAIN_TYPE_GOOD_GENE_COMBO = [LOCI_19[1], LOCI_25[1], LOCI_28[1], LOCI_29[1]]
BRAIN_TYPE_BAD_GENE_COMBO = [LOCI_19[8], LOCI_25[2], LOCI_28[2], LOCI_29[2]]
BRAIN_TYPE_WORST_GENE_COMBO = [LOCI_19[3], LOCI_25[3], LOCI_28[3], LOCI_29[3]]

TORSO_GENE_COMBOS = {
    tuple(TORSO_OPTIMAL_GENE_COMBO): 2,
    tuple(TORSO_GOOD_GENE_COMBO): 1.5,
    tuple(TORSO_BAD_GENE_COMBO): 0.5,
    tuple(TORSO_WORST_GENE_COMBO): 0.25,
}
ARM_LENGTH_GENE_COMBOS = {
    tuple(ARM_LENGTH_OPTIMAL_GENE_COMBO): 2,
    tuple(ARM_LENGTH_GOOD_GENE_COMBO): 1.5,
    tuple(ARM_LENGTH_BAD_GENE_COMBO): 0.5,
    tuple(ARM_LENGTH_WORST_GENE_COMBO): 0.25,
}
LEG_LENGTH_GENE_COMBOS = {
    tuple(LEG_LENGTH_OPTIMAL_GENE_COMBO): 2,
    tuple(LEG_LENGTH_GOOD_GENE_COMBO): 1.5,
    tuple(LEG_LENGTH_BAD_GENE_COMBO): 0.5,
    tuple(LEG_LENGTH_WORST_GENE_COMBO): 0.25,
}
MUSCLULATURE_GENE_COMBOS = {
    tuple(MUSCLULATURE_OPTIMAL_GENE_COMBO): 2,
    tuple(MUSCLULATURE_GOOD_GENE_COMBO): 1.5,
    tuple(MUSCLULATURE_BAD_GENE_COMBO): 0.5,
    tuple(MUSCLULATURE_WORST_GENE_COMBO): 0.25,
}
METABOLISM_GENE_COMBOS = {
    tuple(METABOLISM_OPTIMAL_GENE_COMBO): 2,
    tuple(METABOLISM_GOOD_GENE_COMBO): 1.5,
    tuple(METABOLISM_BAD_GENE_COMBO): 0.5,
    tuple(METABOLISM_WORST_GENE_COMBO): 0.25,
}
FLEXIBILITY_GENE_COMBOS = {
    tuple(FLEXIBILITY_OPTIMAL_GENE_COMBO): 2,
    tuple(FLEXIBILITY_GOOD_GENE_COMBO): 1.5,
    tuple(FLEXIBILITY_BAD_GENE_COMBO): 0.5,
    tuple(FLEXIBILITY_WORST_GENE_COMBO): 0.25,
}
PAIN_TOLERANCE_GENE_COMBOS = {
    tuple(PAIN_TOLERANCE_OPTIMAL_GENE_COMBO): 2,
    tuple(PAIN_TOLERANCE_GOOD_GENE_COMBO): 1.5,
    tuple(PAIN_TOLERANCE_BAD_GENE_COMBO): 0.5,
    tuple(PAIN_TOLERANCE_WORST_GENE_COMBO): 0.25,
}
EYE_COLOR_GENE_COMBOS = {
    tuple(EYE_COLOR_OPTIMAL_GENE_COMBO): 2,
    tuple(EYE_COLOR_GOOD_GENE_COMBO): 1.5,
    tuple(EYE_COLOR_BAD_GENE_COMBO): 0.5,
    tuple(EYE_COLOR_WORST_GENE_COMBO): 0.25,
}
VISION_GENE_COMBOS = {
    tuple(VISION_OPTIMAL_GENE_COMBO): 2,
    tuple(VISION_GOOD_GENE_COMBO): 1.5,
    tuple(VISION_BAD_GENE_COMBO): 0.9,
    tuple(VISION_WORST_GENE_COMBO): 0.1,
}
HEARING_GENE_COMBOS = {
    tuple(HEARING_OPTIMAL_GENE_COMBO): 2,
    tuple(HEARING_GOOD_GENE_COMBO): 1.5,
    tuple(HEARING_BAD_GENE_COMBO): 0.5,
    tuple(HEARING_WORST_GENE_COMBO): 0.25,
}
BLOOD_TYPE_GENE_COMBOS = {
    tuple(BLOOD_TYPE_OPTIMAL_GENE_COMBO): 2,
    tuple(BLOOD_TYPE_GOOD_GENE_COMBO): 1.5,
    tuple(BLOOD_TYPE_BAD_GENE_COMBO): 0.5,
    tuple(BLOOD_TYPE_WORST_GENE_COMBO): 0.25,
}
LUNG_CAPACITY_GENE_COMBOS = {
    tuple(LUNG_CAPACITY_OPTIMAL_GENE_COMBO): 2,
    tuple(LUNG_CAPACITY_GOOD_GENE_COMBO): 1.5,
    tuple(LUNG_CAPACITY_BAD_GENE_COMBO): 0.5,
    tuple(LUNG_CAPACITY_WORST_GENE_COMBO): 0.25,
}
REGENERATION_GENE_COMBOS = {
    tuple(REGENERATION_OPTIMAL_GENE_COMBO): 2,
    tuple(REGENERATION_GOOD_GENE_COMBO): 1.5,
    tuple(REGENERATION_BAD_GENE_COMBO): 0.5,
    tuple(REGENERATION_WORST_GENE_COMBO): 0.25,
}
HAIR_COLOR_GENE_COMBOS = {
    tuple(HAIR_COLOR_OPTIMAL_GENE_COMBO): 2,
    tuple(HAIR_COLOR_GOOD_GENE_COMBO): 1.5,
    tuple(HAIR_COLOR_BAD_GENE_COMBO): 0.5,
    tuple(HAIR_COLOR_WORST_GENE_COMBO): 0.25,
}
HAIR_TYPE_GENE_COMBOS = {
    tuple(HAIR_TYPE_OPTIMAL_GENE_COMBO): 2,
    tuple(HAIR_TYPE_GOOD_GENE_COMBO): 1.5,
    tuple(HAIR_TYPE_BAD_GENE_COMBO): 0.5,
    tuple(HAIR_TYPE_WORST_GENE_COMBO): 0.25,
}
BRAIN_TYPE_GENE_COMBOS = {
    tuple(BRAIN_TYPE_OPTIMAL_GENE_COMBO): 2,
    tuple(BRAIN_TYPE_GOOD_GENE_COMBO): 1.5,
    tuple(BRAIN_TYPE_BAD_GENE_COMBO): 0.5,
    tuple(BRAIN_TYPE_WORST_GENE_COMBO): 0.25,
}

#"HEIGHT"
#"ARM_LENGTH"
#"LEG_LENGTH"
#"MUSCULATURE_TYPE"
#"METABOLISM"
#"FLEXIBILITY"
#"PAIN_TOLERANCE"
#"EYE_SIGHT"
#"HEARING"
#"BLOOD_TYPE"
#"LUNG_CAPACITY"
#"REGENERATION"